### ISSUE TITLE
CNEFinder for whole geonome

### ISSUE THREAD

**Issue by binlu1981** [lorrainea/CNEFinder#9]
Hi, 
Can CNEFinder work for entire genome assembly rather than limit to specific chromosomes?

Bin

**Comment by lorrainea** [comment]
Hi Bin

Strictly it does not but internally the code can do this using the following method to allow CNEFinder to work on an entire genome rather than a specific chromosome:
1. Concatenate all chromosomes into a single Fasta file.
2. Instead of inputting the chromosome name for parameters x and y, use the id name you have given for the Fasta file above.
Let me know if this works for you.
